# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone › https://zones.arilyn.cc
timezone: Asia/Bangkok

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Smith Jirawiboonwet

tagline: Computer Science Student | Cybersecurity & Penetration Testing

description: >-
  Computer Science student focused on Cybersecurity, Penetration Testing,
  and hands-on security labs.

# Fill in the protocol & hostname for your site.
url: "https://teet44182-sketch.github.io"

github:
  username: teet44182-sketch

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Smith Jirawiboonwet
  email: teet44182@gmail.com
  fediverse_handle:
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/teet44182-sketch/
    - https://profile.hackthebox.com/profile/019e66b8-8772-7275-9684-cbe0799eb9f4

# Site Verification Settings
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider:

# Prefer color scheme setting.
theme_mode: dark # [light | dark]

# The CDN endpoint for media resources.
cdn:

# the avatar on sidebar, support local or CORS resources
avatar: 'assets/img/kisaki.png'

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image:

# boolean type, the global switch for TOC in posts.
toc: true

actions:
  # Display "Edit this post" action on each post page to encourage contributions.
  edit_post:
    enabled: false
    url: ""
    static_url: false

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Self-hosted static assets, optional
assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/